In [2]:
import pandas as pd

In [13]:
df = pd.read_csv("data/student_daily_metrics.csv")

In [6]:
display(df.head())
display(df.info())

,student_id,date,session_attended_min,practice_questions,last_quiz_score,days_until_next_quiz
0,S001,2025-10-01,88.0,18,NaN,9
1,S001,2025-10-02,90.0,22,NaN,8
2,S001,2025-10-03,87.0,15,NaN,7
3,S001,2025-10-04,85.0,20,NaN,6
4,S001,2025-10-07,90.0,25,NaN,5

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            2000 non-null   object
 1   date                  2000 non-null   object
 2   session_attended_min  1997 non-null   float64
 3   practice_questions    2000 non-null   int64
 4   last_quiz_score       601 non-null    float64
 5   days_until_next_quiz  2000 non-null   int64
dtypes: float64(2), int64(2), object(2)
memory usage: 93.9+ KB

None

In [ ]:
df[df['session_attended_min'].isna()] # Check rows where session_attended_min is NaN to understand the context of these missing values.

,student_id,date,session_attended_min,practice_questions,last_quiz_score,days_until_next_quiz
117,S012,2025-10-10,NaN,0,28.0,10
415,S042,2025-10-08,NaN,0,82.0,4
1447,S145,2025-10-10,NaN,0,0.0,10

In [20]:
df[(df['session_attended_min']> 90) | (df['session_attended_min'] < 0)] # Check for any outliers in session_attended_min, as it should be between 0 and 90 minutes.

Empty DataFrame
Columns: [student_id, date, session_attended_min, practice_questions, last_quiz_score, days_until_next_quiz]
Index: []

In [15]:
df['session_attended_min'] = df['session_attended_min'].fillna(0) # Fill NaN values with 0, since practice questions were 0, we can assume that the student did not attend the session if the value is NaN.